name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ec2-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Copy binary to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 68.183.127.248
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/release/realestate"
          target: "/root/app/releases/"

      - name: Activate release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 68.183.127.248
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            chmod +x /root/app/releases/realestate

            mv /root/app/releases/realestate /root/app/releases/realestate_${{ github.sha}}

            ln -sfn /root/app/releases/realestate_${{ github.sha}} /root/app/current

            systemctl restart myapp
            sleep 2
            systemctl status myapp --no-pager

      - name: Verify binary exists
        run: |
             ls -lah target/release/
              file target/release/realestate
